TeamSpark.AzureDay.WebSite.Host/Models/Home/IndexModel.cs
namespace TeamSpark.AzureDay.WebSite.Host.Models.Home
{
	public sealed class IndexModel
	{
		public SpeakersModel Speakers { get; set; }
		public PartnersModel Partners { get; set; }
	}
}

TeamSpark.AzureDay.WebSite.Host/Models/Home/PartnersModel.cs
using System.Collections.Generic;
using TeamSpark.AzureDay.WebSite.App.Entity;
using TeamSpark.AzureDay.WebSite.Data.Enum;

namespace TeamSpark.AzureDay.WebSite.Host.Models.Home
{
	public sealed class PartnersModel
	{
		public Dictionary<PartnerType, List<Partner>> PartnersCollection { get; set; }
	}
}

TeamSpark.AzureDay.WebSite.Host/Models/Home/ScheduleModel.cs
using System.Collections.Generic;
using TeamSpark.AzureDay.WebSite.App.Entity;

namespace TeamSpark.AzureDay.WebSite.Host.Models.Home
{
	public sealed class ScheduleModel
	{
		public List<Room> Rooms { get; set; }

		public List<List<Timetable>> Timetables { get; set; }
	}
}

TeamSpark.AzureDay.WebSite.Host/Models/Home/SpeakersModel.cs
using System.Collections.Generic;
using TeamSpark.AzureDay.WebSite.App.Entity;

namespace TeamSpark.AzureDay.WebSite.Host.Models.Home
{
	public sealed class SpeakersModel
	{
		public List<List<Speaker>> SpeakersCollections { get; set; }
	}
}

TeamSpark.AzureDay.WebSite.Host/Controllers/Api/ScheduleController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;

namespace TeamSpark.AzureDay.WebSite.Host.Controllers.Api
{
    public class ScheduleController : ApiController
    {
		[HttpGet]
		[Route("api/schedule/selected")]
		//[Authorize]
	    public async Task<List<string>> GetSelectedTopics()
		{
			return new List<string>();
		}

		[HttpPost]
		[Route("api/schedule/{topicId}")]
		//[Authorize]
		public async Task SelectTopic(string topicId)
		{
			
		}

		[HttpDelete]
		[Route("api/schedule/{topicId}")]
		//[Authorize]
		public async Task UnselectTopic(string topicId)
		{

		}
	}
}

TeamSpark.AzureDay.WebSite.Host/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Security;
using TeamSpark.AzureDay.WebSite.App;
using TeamSpark.AzureDay.WebSite.App.Entity;
using TeamSpark.AzureDay.WebSite.Data.Enum;
using TeamSpark.AzureDay.WebSite.Host.Filter;
using TeamSpark.AzureDay.WebSite.Host.Models.Home;

namespace TeamSpark.AzureDay.WebSite.Host.Controllers
{
	public class HomeController : Controller
	{
		public async Task<ActionResult> Index()
		{
			var speakersTask = AppFactory.SpeakerService.Value.GetSpeakersAsync();
			var partnersTask = AppFactory.PartnerService.Value.GetPartnersAsync();

			var model = new IndexModel
			{
				Speakers = new SpeakersModel
				{
					SpeakersCollections = new List<List<Speaker>>()
				},
				Partners = new PartnersModel
				{
					PartnersCollection = new Dictionary<PartnerType, List<Partner>>()
				}
			};

			await Task.WhenAll(
				speakersTask,
				partnersTask
			);

			var speakers = speakersTask.Result;
			var i = 0;
			foreach (var speaker in speakers)
			{
				List<Speaker> list;
				if (i == 0)
				{
					list = new List<Speaker>();
					model.Speakers.SpeakersCollections.Add(list);
				}
				else
				{
					list = model.Speakers.SpeakersCollections.Last();
				}

				list.Add(speaker);

				if (i == 3)
				{
					i = 0;
				}
				else
				{
					i++;
				}
			}

			var partners = partnersTask.Result;
			model.Partners.PartnersCollection = partners
				.GroupBy(p => p.PartnerType)
				.ToDictionary(p => p.Key, group => group.OrderBy(p => p.OrderN).ToList());

			return View(model);
		}

		public async Task<ActionResult> Schedule()
		{
			var roomsTask = AppFactory.RoomService.Value.GetAllRoomsAsync();
			var timetableTask = AppFactory.TimetableService.Value.GetTimetableAsync();

			await Task.WhenAll(
				roomsTask,
				timetableTask
			);

			var model = new ScheduleModel();

			model.Rooms = roomsTask.Result
				.Where(r => r.RoomType != RoomType.CoffeeRoom)
				.OrderBy(r => r.ColorNumber)
				.ToList();

			model.Timetables = timetableTask.Result
				.GroupBy(
					t => t.TimeStartHours * 100 + t.TimeStartMinutes,
					(key, timetables) => timetables.OrderBy(t => t.Room.ColorNumber).ToList())
				.ToList();

			return View(model);
		}

		public async Task<ActionResult> Partners()
		{
			var model = new PartnersModel();

			model.PartnersCollection = (await AppFactory.PartnerService.Value.GetPartnersAsync())
				.GroupBy(p => p.PartnerType)
				.ToDictionary(p => p.Key, group => group.OrderBy(p => p.OrderN).ToList());

			return View(model);
		}

		[NonAuthorize]
		public async Task<ActionResult> Redirect([FromUri] string quickAuthToken, [FromUri] string redirectUrl)
		{
			var authToken = await AppFactory.QuickAuthTokenService.Value.GetQuickAuthTokenByValueAsync(quickAuthToken, false);

			if (authToken != null)
			{
				var attendee = await AppFactory.AttendeeService.Value.GetAttendeeByEmailAsync(authToken.Email);
				if (attendee != null && attendee.IsConfirmed)
				{
					FormsAuthentication.SetAuthCookie(attendee.EMail, true);
					await AppFactory.QuickAuthTokenService.Value.ExpireTokenByValueAsync(quickAuthToken);
				}
			}

			return Redirect(redirectUrl);
		}
	}
}

TeamSpark.AzureDay.WebSite.Host/Controllers/LayoutController.cs
using System.Web.Mvc;

namespace TeamSpark.AzureDay.WebSite.Host.Controllers
{
	public class LayoutController : Controller
	{
		[ChildActionOnly]
		public ActionResult Header()
		{
			return View("_Header");
		}

		[ChildActionOnly]
		public ActionResult Banner()
		{
			return View("_Banner");
		}

		[ChildActionOnly]
		public ActionResult Footer()
		{
			return View("_Footer");
		}
	}
}

TeamSpark.AzureDay.WebSite.Host/Views/Home/Index.cshtml
@model TeamSpark.AzureDay.WebSite.Host.Models.Home.IndexModel

@{
	ViewBag.Title = "AzureDay 2016";
}

<div class="boxedcontent">
	@Html.Action("Header", "Layout")

	@Html.Action("Banner", "Layout")

	<section class="introblock whites">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h1>
						<span class="animated fadeInDown">
							AZUREDAY 2016 - 2я специализированная <span class='colortext'>облачная</span> конференция в Украине, -<br>
							это технологии, люди, опыт, инновации и сообщество профессионалов.
						</span>
					</h1>
				</div>
			</div>
		</div>
	</section>
<!-- end introblock -->

<section class="service-box whites">
		<div class="container">
			<div class="row">
				<div class="col-md-3 text-center">
					<div class="icon-box-top">
						<a href="#">
							<i class="fontawesome-icon medium circle-white center fa fa-plane"></i>
						</a>
						<h1>ЗА ПРЕДЕЛАМИ УКРАИНЫ</h1>
						<p>
							Зарубежные докладчики, слушатели и последователи конференции в других странах.
						</p>
					</div>
				</div>
				<div class="col-md-3 text-center">
					<div class="icon-box-top active">
						<a href="#">
							<i class="fontawesome-icon medium circle-white center fa fa-rocket"></i>
						</a>
						<h1>ИДЕИ И ИННОВАЦИИ</h1>
						<p>
							Опыт и инновации из мира облаков, представленные экспертами украинского и зарубежного рынков.
						</p>
					</div>
				</div>
				<div class="col-md-3 text-center">
					<div class="icon-box-top">
						<a href="#">
							<i class="fontawesome-icon medium circle-white center fa fa-code"></i>
						</a>
						<h1>ПРИМЕРЫ И ПРАКТИКА</h1>
						<p>
							Все докладчики имеют богатый практический опыт. Отдельно представлен поток лабораторных работ.
						</p>
					</div>
				</div>
				<div class="col-md-3 text-center">
					<div class="icon-box-top">
						<a href="#">
							<i class="fontawesome-icon medium circle-white center fa fa-users"></i>
						</a>
						<h1>СООБЩЕСТВО И КОНТАКТЫ</h1>
						<p>
							Станьте частью облачного сообщества и познакомьтесь с новыми коллегами, партнерами, сотрудниками.
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end servicesbox -->

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="titleborder center">
					<div>
						<h1 class="animated fadeInDownBig">Кратко об AZUREDAY</h1>
					</div>
				</div>

				<div class="shortcode row">
					<div class="col-md-6">
						<!-- begin box shadow -->
						<div class="box effect2">
							Цель AZUREDAY -  собрать вместе профессионалов, которые уже имеют <span class='colortext'>практический опыт использования Azure</span>, а также новичков, которые только начинают с ним работать, для эффективного обмена опытом и знаниями.
						</div>
						<!-- end box shadow -->
					</div>
					<div class="col-md-6">
						<div class="box effect2">
							На AZUREDAY планируется организовать <span class='colortext'>распределённые потоки докладов</span>, которые смогут наиболее полно покрыть всю гамму направлений работы с облачными технологиями.
						</div>
					</div>
				</div>

				<div class="shortcode row">
					<div class="col-md-6">
						<!-- begin box shadow -->
						<div class="box effect6">
							Докладчики на AZUREDAY - как украинские, так и приглашенные из других стран облачные эксперты и владельцы бизнеса.
						</div>
						<!-- end box shadow -->
					</div>
					<div class="col-md-6">
						<div class="box effect6">
							Участие в AZUREDAY платное, <span class='colortext'>в стоимость билета входят кофе брейки</span>. Есть скидки для студентов, партнёров и скидки по программе early bird.
						</div>
					</div>
				</div>

			</div>
		</div>

	</div>

	<section class="bgsizecover" style="background-image: url('Theme/img/_bgnd/bgnd02b.jpg'); background-attachment: fixed; background-position: relative; height: 250px;">
		<div class="transp">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
					</div>
					<div class="col-md-6 text-center">
						<h1 class="maintitle" style="color: #fff;"></h1>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end parallax -->

	<section class="introblock whites">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h1>
						<span class="animated fadeInRightBig">На AZUREDAY будут <span class='colortext'>распределённые потоки докладов</span>, которые смогут наиболее полно покрыть всю гамму направлений работы с облачными технологиями, <br />а также отдельный поток <span class='colortext'>лабораторных работ</span>.</span>
					</h1>
				</div>
			</div>
		</div>
	</section>

	@Html.Partial("_Speakers", Model.Speakers)

	<section class="bgsizecover" style="background-image: url('Theme/img/_bgnd/bgnd03b.jpg'); background-attachment: fixed; background-position: relative; height: 250px;">
		<div class="transp">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
					</div>
					<div class="col-md-6 text-center">
						<h1 class="maintitle" style="color: #fff;"></h1>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end parallax -->

	<div class="container">
		<div class="row">
			<div class="panel1">
				<div class="col-md-9">
					<h4 class="animated fadeInLeft">Хотите поддержать AZUREDAY?</h4>
					Если вы хотите поддержать AZUREDAY - предоставить конференции докладчика, призы для участников или же стать информационным партнёром, - принимайте участие в нашей партнерской программе.<br />
					Более подробно о партнерской программе вы можете узнать, связавшись с организаторами конференции.
				</div>
				<div class="col-md-3">
					<a href="mailto:partner@azureday.net" class="sbutton square noshadow medium mainthemebgcolor"><i class="fa fa-comment"></i> Свяжитесь с нами</a>
				</div>
				<div class="clearfix">
				</div>
			</div>
			<!-- end panel -->
		</div>
	</div>

	@Html.Partial("_Partners", Model.Partners)

	<section class="infoarea whites">
		<div class="container">
			<div class="row text-center">
				<div class="col-md-12">
					<h1 class="maintitle">Каким партнером вы хотите стать?</h1>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-star infoareaicon"></i>
					<div class="infoareawrap">
						<h1 class="text-center subtitle">Золотой партнер</h1>
						<p>
							Поддержите конференцию финансово, помогая со средствами на обеды и кофе-брейки для участников.
						</p>
						<p class='text-center'>
							<a href='mailto:partner@azureday.net'>Свяжитесь с нами</a>
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-moon-o infoareaicon"></i>
					<div class="infoareawrap">
						<h1 class="text-center subtitle">Партнер по призам</h1>
						<p>
							Предоставьте свои призы и/или сувениры для розыграша или распространения среди участников конференции.
						</p>
						<p class='text-center'>
							<a href='mailto:partner@azureday.net'>Свяжитесь с нами</a>
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-bullhorn infoareaicon"></i>
					<div class="infoareawrap">
						<h1 class="text-center subtitle">Информационный партнер</h1>
						<p>
							Помогите распространить информацию о конференции среди своих партнеров и/или клиентов. 
						</p>
						<p class='text-center'>
							<a href='mailto:partner@azureday.net'>Свяжитесь с нами</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end infoarea -->

	

	@*<section class="homerecentportfolio grays">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="heading">
						Как это было в 2015 году<a href="#">/ Смотреть галерею</a>
					</h1>
					<div class="recent-portfolio">
						<div class="list_carousel">
							<div class="carousel_nav">
								<a class="prev" id="car_prev" href="#"><span>prev</span></a><a class="next" id="car_next" href="#"><span>next</span></a>
							</div>
							<div class="clearfix">
							</div>
							<ul id="recent-portfolio">
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/tumblr_mvyxfkaRb41st5lhmo1_1280-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="tumblr_mvyxfkaRb41st5lhmo1_1280" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/tumblr_mvyxfkaRb41st5lhmo1_1280.jpg" title="Asher Theme"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">Asher Theme</a></h1>
										<p>
											multipurpose theme
										</p>
									</div>
								</li>
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/tumblr_mvyxgqpNHE1st5lhmo1_1280-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="tumblr_mvyxgqpNHE1st5lhmo1_1280" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/tumblr_mvyxgqpNHE1st5lhmo1_1280.jpg" title="WowThemes"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">WowThemes</a></h1>
										<p>
											biscaya author
										</p>
									</div>
								</li>
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/post1-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="post1" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2014/02/post1.jpg" title="Salique"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">Salique</a></h1>
										<p>
											multipurpose template
										</p>
									</div>
								</li>
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_mzzr7n7idZ1st5lhmo1_1280-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="tumblr_mzzr7n7idZ1st5lhmo1_1280" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_mzzr7n7idZ1st5lhmo1_1280.jpg" title="Serenity"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">Serenity</a></h1>
										<p>
											wordpress portfolio
										</p>
									</div>
								</li>
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_mzzqwktTbR1st5lhmo1_1280-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="tumblr_mzzqwktTbR1st5lhmo1_1280" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_mzzqwktTbR1st5lhmo1_1280.jpg" title="BizLeaders"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">BizLeaders</a></h1>
										<p>
											business html
										</p>
									</div>
								</li>
								<li>
									<div class="boxcontainer">
										<a class="imgOpa imgproject" href="portfoliosingle.html"><img width="600" height="350" src="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_myp9dgyhJ71st5lhmo1_1280-600x350.jpg" class="attachment-recentprojects-thumb wp-post-image" alt="tumblr_myp9dgyhJ71st5lhmo1_1280" /></a>
										<div class="roll">
											<div class="wrapcaption">
												<a href="portfoliosingle.html"><i class="fa fa-link captionicons"></i></a><a data-gal="prettyPhoto[gallery1]" href="http://www.wowthemes.net/demo-asher/wp-content/uploads/sites/9/2013/08/tumblr_myp9dgyhJ71st5lhmo1_1280.jpg" title="Studio"><i class="fa fa-search-plus captionicons"></i></a>
											</div>
										</div>
										<h1><a href="portfoliosingle.html">Vesta</a></h1>
										<p>
											wordpress theme
										</p>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="clearfix">
					</div>
				</div>
			</div>
		</div>
	</section>*@
	<!-- end homerecentportfolio -->
 
	@Html.Action("Footer", "Layout")

</div><!-- end boxedcontent -->

TeamSpark.AzureDay.WebSite.Host/Views/Home/Partners.cshtml
@using TeamSpark.AzureDay.WebSite.Data.Enum
@model TeamSpark.AzureDay.WebSite.Host.Models.Home.PartnersModel
@{
	ViewBag.Title = "AzureDay 2016 - партнеры";
}

<div class="boxedcontent">
	@Html.Action("Header", "Layout")

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="titleborder center">
					<div>
						<h1 class="maintitle animated fadeInDownBig">Партнеры AZUREDAY</h1>
					</div>
				</div>
			</div>
		</div>

		@foreach (var partnersKey in Model.PartnersCollection.Keys)
		{
			var css = string.Empty;
			switch (partnersKey)
			{
				case PartnerType.VIP:
					css = "fa-diamond";
					break;
				case PartnerType.Gold:
					css = "fa-star";
					break;
				case PartnerType.Silver:
					css = "fa-star";
					break;
				case PartnerType.Raffle:
					css = "fa-gift";
					break;
				case PartnerType.Info:
					css = "fa-bullhorn";
					break;
				case PartnerType.Speaker:
					css = "fa-commenting-o";
					break;
				case PartnerType.Tech:
					css = "fa-cogs";
					break;
			}
			foreach (var partner in Model.PartnersCollection[partnersKey])
			{
				<div class="row padding15">
					<div class="col-md-2 text-center">
						<div class="icon-box-top active">
							<i class="fontawesome-icon medium circle-white center fa @css"></i>
							<p>@partner.PartnerType.ToDisplayStringPartner()</p>
						</div>
					</div>
					<div class="col-md-3">
						<img src="@partner.LogoUrl" alt="@partner.Title" class="img-responsive" />
					</div>
					<div class="col-md-5 text-justify">
						@partner.Description
					</div>
					<div class="col-md-2">
						<a href="@partner.WebUrl" target="_blank" style="white-space: nowrap;">@partner.WebUrl</a>
					</div>
				</div>
			}
		}
	</div>

	@Html.Action("Footer", "Layout")
</div>

TeamSpark.AzureDay.WebSite.Host/Views/Home/Schedule.cshtml
@using TeamSpark.AzureDay.WebSite.Data.Enum
@model TeamSpark.AzureDay.WebSite.Host.Models.Home.ScheduleModel

@{
	ViewBag.Title = "AzureDay 2016 - расписание";
}

<div class="boxedcontent">
	@Html.Action("Header", "Layout")

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="titleborder center">
					<div>
						<h1 class="animated fadeInDownBig">Расписание AZUREday</h1>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			@for (var i = 0; i < Model.Rooms.Count; i++)
			{
				<div class="col-md-3 col-sm-3">
					<div class="box effect2 @string.Format("myAreaContainer{0}", Model.Rooms[i].ColorNumber)">
						@Model.Rooms[i].Title
					</div>
				</div>
			}
		</div>

		@foreach (var timetables in Model.Timetables)
		{
			<div class="row">
				@if (timetables.Count == 1)
				{
					if (timetables[0].Room.RoomType == RoomType.CoffeeRoom)
					{
						<div class="col-md-12 col-sm-12">
							<div class="box">
								<div class="mySlotTime">
									@string.Format("{0}:{1}", timetables[0].TimeStartHours, timetables[0].TimeStartMinutes.ToString("D2")) -
									@string.Format("{0}:{1}", timetables[0].TimeEndHours, timetables[0].TimeEndMinutes.ToString("D2"))
								</div>
								<div style="text-align: center;">
									<i>@timetables[0].Topic.Title</i>
								</div>
							</div>
						</div>
					}
					else
					{
						<div class="col-md-12 col-sm-12">
							<div class="box effect6 myAreaBoxBorder1">
								<div class="mySlotTime">
									@string.Format("{0}:{1}", timetables[0].TimeStartHours, timetables[0].TimeStartMinutes.ToString("D2")) -
									@string.Format("{0}:{1}", timetables[0].TimeEndHours, timetables[0].TimeEndMinutes.ToString("D2"))
								</div>
								@if (timetables[0].Topic.Speakers.Any())
								{
								<div class="mySlotAuthor">
									@string.Join(", ", timetables[0].Topic.Speakers.Select(s => s.FullName))
								</div>
								}
								<div style="text-align: center;">
									<b>@timetables[0].Topic.Title</b><br /><br />
									@if (timetables[0].Topic.Language != null && !string.IsNullOrEmpty(timetables[0].Topic.Language.Title))
									{
										@Html.Raw(string.Format("Язык: {0}", timetables[0].Topic.Language.Title))
									}
									@*@timetables[0].Topic.Description*@
								</div>
							</div>
						</div>
					}
				}
				else
				{
					for (var i = 0; i < timetables.Count; i++)
					{
						<div class="col-md-3 col-sm-3" style="@Html.Raw(timetables[i].HasLanguage ? string.Empty : "opacity: 0.5;")">
							<div class="box effect2 @string.Format("myAreaBoxBorder{0}", timetables[i].Room.ColorNumber)">
								<div class="mySlotTime">
									@string.Format("{0}:{1}", timetables[i].TimeStartHours, timetables[i].TimeStartMinutes.ToString("D2")) -
									@string.Format("{0}:{1}", timetables[i].TimeEndHours, timetables[i].TimeEndMinutes.ToString("D2"))
								</div>
								@if (timetables[i].Topic.Speakers.Any())
								{
									<div class="mySlotAuthor">
										@Html.Raw(string.Join(",<br/>", timetables[i].Topic.Speakers.Select(s => s.FullName)))
									</div>
								}
								<div>
									<b>@timetables[i].Topic.Title</b><br /><br />
									@if (timetables[i].HasLanguage)
									{
										@Html.Raw(string.Format("Язык: {0}<br /><br />", timetables[i].Topic.Language.Title))
									}
									@timetables[i].Topic.Description
								</div>
							</div>
						</div>
					}
				}
			</div>
		}

	</div>

	@Html.Action("Footer", "Layout")

</div><!-- end boxedcontent -->